# Generated by Django 5.2 on 2025-09-25 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
                ('content', models.TextField(verbose_name='Contenido')),
                ('excerpt', models.TextField(max_length=300, verbose_name='Extracto')),
                ('featured_image', models.ImageField(blank=True, upload_to='blog/', verbose_name='Imagen destacada')),
                ('post_type', models.CharField(choices=[('news', 'Noticia'), ('tutorial', 'Tutorial'), ('opinion', 'Opinión'), ('project', 'Proyecto'), ('career', 'Carrera')], default='news', max_length=20, verbose_name='Tipo de post')),
                ('tags', models.CharField(blank=True, help_text='Tags separados por comas', max_length=200, verbose_name='Tags')),
                ('status', models.CharField(choices=[('draft', 'Borrador'), ('published', 'Publicado'), ('archived', 'Archivado')], default='draft', max_length=10, verbose_name='Estado')),
                ('publish_date', models.DateTimeField(verbose_name='Fecha de publicación')),
                ('reading_time', models.PositiveIntegerField(default=5, verbose_name='Tiempo de lectura (minutos)')),
                ('featured', models.BooleanField(default=False, verbose_name='Post destacado')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Post del Blog',
                'verbose_name_plural': 'Posts del Blog',
                'ordering': ['-publish_date'],
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('subject', models.CharField(max_length=200, verbose_name='Asunto')),
                ('message', models.TextField(verbose_name='Mensaje')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de envío')),
                ('read', models.BooleanField(default=False, verbose_name='Leído')),
            ],
            options={
                'verbose_name': 'Mensaje de Contacto',
                'verbose_name_plural': 'Mensajes de Contacto',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution', models.CharField(max_length=200, verbose_name='Institución')),
                ('degree', models.CharField(max_length=200, verbose_name='Título/Certificación')),
                ('field_of_study', models.CharField(max_length=200, verbose_name='Campo de estudio')),
                ('education_type', models.CharField(choices=[('formal', 'Educación Formal'), ('online_course', 'Curso Online'), ('certification', 'Certificación'), ('bootcamp', 'Bootcamp'), ('workshop', 'Taller/Workshop')], default='formal', max_length=20, verbose_name='Tipo de educación')),
                ('start_date', models.DateField(verbose_name='Fecha de inicio')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Fecha de fin')),
                ('current', models.BooleanField(default=False, verbose_name='En curso')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('credential_id', models.CharField(blank=True, max_length=100, verbose_name='ID del certificado')),
                ('credential_url', models.URLField(blank=True, verbose_name='URL de verificación')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Orden de visualización')),
            ],
            options={
                'verbose_name': 'Educación',
                'verbose_name_plural': 'Educación',
                'ordering': ['-end_date', '-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=200, verbose_name='Empresa')),
                ('position', models.CharField(max_length=200, verbose_name='Posición')),
                ('description', models.TextField(verbose_name='Descripción del trabajo')),
                ('start_date', models.DateField(verbose_name='Fecha de inicio')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Fecha de fin')),
                ('current', models.BooleanField(default=False, verbose_name='Trabajo actual')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Orden de visualización')),
            ],
            options={
                'verbose_name': 'Experiencia',
                'verbose_name_plural': 'Experiencias',
                'ordering': ['-start_date', 'order'],
            },
        ),
        migrations.CreateModel(
            name='PageVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_url', models.CharField(max_length=500, verbose_name='URL de la página')),
                ('page_title', models.CharField(max_length=200, verbose_name='Título de la página')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y hora')),
                ('ip_address', models.GenericIPAddressField(verbose_name='Dirección IP')),
                ('user_agent', models.TextField(verbose_name='User Agent')),
            ],
            options={
                'verbose_name': 'Visita de Página',
                'verbose_name_plural': 'Visitas de Páginas',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('title', models.CharField(max_length=200, verbose_name='Título profesional')),
                ('bio', models.TextField(verbose_name='Biografía')),
                ('profile_image', models.ImageField(upload_to='profile/', verbose_name='Foto de perfil')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Teléfono')),
                ('location', models.CharField(max_length=100, verbose_name='Ubicación')),
                ('linkedin_url', models.URLField(blank=True, verbose_name='URL de LinkedIn')),
                ('github_url', models.URLField(blank=True, verbose_name='URL de GitHub')),
                ('resume_pdf', models.FileField(blank=True, upload_to='profile/', verbose_name='CV en PDF')),
                ('show_web_resume', models.BooleanField(default=True, verbose_name='Mostrar CV web')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Perfil',
                'verbose_name_plural': 'Perfiles',
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre de la habilidad')),
                ('proficiency', models.IntegerField(choices=[(1, 'Básico'), (2, 'Intermedio'), (3, 'Avanzado'), (4, 'Experto')], verbose_name='Nivel de competencia')),
                ('years_experience', models.PositiveIntegerField(verbose_name='Años de experiencia')),
                ('category', models.CharField(help_text='Ej: Frontend, Backend, Tools, Database, etc.', max_length=100, verbose_name='Categoría')),
            ],
            options={
                'verbose_name': 'Habilidad',
                'verbose_name_plural': 'Habilidades',
                'ordering': ['category', '-proficiency', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Technology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Nombre')),
                ('icon', models.CharField(blank=True, help_text='Clase CSS para mostrar el icono (ej: fab fa-python)', max_length=50, verbose_name='Clase CSS del icono')),
                ('color', models.CharField(default='#000000', help_text='Color en formato hexadecimal (ej: #FF5733)', max_length=7, verbose_name='Color')),
            ],
            options={
                'verbose_name': 'Tecnología',
                'verbose_name_plural': 'Tecnologías',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('slug', models.SlugField(help_text='URL amigable generada automáticamente', unique=True, verbose_name='Slug')),
                ('description', models.TextField(verbose_name='Descripción breve')),
                ('detailed_description', models.TextField(verbose_name='Descripción detallada')),
                ('image', models.ImageField(upload_to='projects/', verbose_name='Imagen principal')),
                ('github_url', models.URLField(blank=True, verbose_name='URL de GitHub')),
                ('demo_url', models.URLField(blank=True, verbose_name='URL de demostración')),
                ('visibility', models.CharField(choices=[('public', 'Público'), ('private', 'Privado')], default='public', max_length=10, verbose_name='Visibilidad')),
                ('featured', models.BooleanField(default=False, verbose_name='Proyecto destacado')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Orden de visualización')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('technologies', models.ManyToManyField(to='portfolio.technology', verbose_name='Tecnologías utilizadas')),
            ],
            options={
                'verbose_name': 'Proyecto',
                'verbose_name_plural': 'Proyectos',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
