# Generated by Django 5.2 on 2025-09-25 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='technology',
            name='color',
            field=models.CharField(default='#000000', help_text='Color en formato hexadecimal. Ejemplos de colores oficiales:<br>• Python: <code>#3776ab</code><br>• JavaScript: <code>#f7df1e</code><br>• React: <code>#61dafb</code><br>• Django: <code>#092e20</code><br>• Docker: <code>#2496ed</code><br>• Git: <code>#f05032</code><br>• AWS: <code>#ff9900</code><br>• PostgreSQL: <code>#336791</code>', max_length=7, verbose_name='Color'),
        ),
        migrations.AlterField(
            model_name='technology',
            name='icon',
            field=models.CharField(blank=True, help_text="Clase CSS para mostrar el icono. Ejemplos comunes:<br>• Python: <code>fab fa-python</code><br>• JavaScript: <code>fab fa-js-square</code><br>• React: <code>fab fa-react</code><br>• Docker: <code>fab fa-docker</code><br>• HTML: <code>fab fa-html5</code><br>• CSS: <code>fab fa-css3-alt</code><br>• Node.js: <code>fab fa-node-js</code><br>• Git: <code>fab fa-git-alt</code><br>• AWS: <code>fab fa-aws</code><br>• Linux: <code>fab fa-linux</code><br><br>📚 <strong>Más iconos disponibles en:</strong><br>🔗 <a href='https://fontawesome.com/icons' target='_blank'>Font Awesome Icons</a><br>🔗 <a href='https://devicon.dev/' target='_blank'>Devicon (Iconos específicos para desarrollo)</a><br>🔗 <a href='https://simpleicons.org/' target='_blank'>Simple Icons</a>", max_length=50, verbose_name='Clase CSS del icono'),
        ),
    ]
