# Generated by Django 5.0.4 on 2025-09-25 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_alter_technology_color_alter_technology_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='emoji',
            field=models.CharField(blank=True, help_text='Emoji para mostrar junto a la descripción (ej: 🚀, 🌐, 📱)', max_length=10, verbose_name='Emoji'),
        ),
        migrations.AddField(
            model_name='project',
            name='forks_count',
            field=models.PositiveIntegerField(default=0, help_text='Para proyectos de GitHub, se actualiza automáticamente', verbose_name='Número de forks'),
        ),
        migrations.AddField(
            model_name='project',
            name='github_owner',
            field=models.CharField(blank=True, help_text='Usuario/organización propietaria del repositorio (ej: microsoft, google)', max_length=100, verbose_name='Propietario GitHub'),
        ),
        migrations.AddField(
            model_name='project',
            name='is_private_project',
            field=models.BooleanField(default=False, help_text='Marcar si es un proyecto privado o de trabajo que no tiene repositorio público', verbose_name='Proyecto privado/trabajo'),
        ),
        migrations.AddField(
            model_name='project',
            name='primary_language',
            field=models.CharField(blank=True, help_text='El lenguaje de programación principal usado (Python, JavaScript, etc.)', max_length=50, verbose_name='Lenguaje principal'),
        ),
        migrations.AddField(
            model_name='project',
            name='project_type',
            field=models.CharField(choices=[('framework', 'Framework'), ('tool', 'Tool'), ('website', 'Website'), ('template', 'Template'), ('dataset', 'Dataset'), ('mobile_app', 'Mobile App'), ('desktop_app', 'Desktop App'), ('library', 'Library'), ('api', 'API'), ('other', 'Other')], default='other', help_text='Categoría del proyecto (Framework, Tool, Website, etc.)', max_length=20, verbose_name='Tipo de proyecto'),
        ),
        migrations.AddField(
            model_name='project',
            name='stars_count',
            field=models.PositiveIntegerField(default=0, help_text='Para proyectos de GitHub, se actualiza automáticamente. Para proyectos privados, puedes agregar un número estimado.', verbose_name='Número de estrellas'),
        ),
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(blank=True, upload_to='projects/', verbose_name='Imagen principal'),
        ),
    ]
