# Generated by Django 5.2 on 2025-09-26 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_project_emoji_project_forks_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='github_url',
            field=models.URLField(blank=True, help_text='Repositorio relacionado con el post', verbose_name='URL de GitHub'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='linkedin_url',
            field=models.URLField(blank=True, help_text='Enlace al post en LinkedIn', verbose_name='URL de LinkedIn'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='medium_url',
            field=models.URLField(blank=True, help_text='Enlace al artículo en Medium', verbose_name='URL de Medium'),
        ),
    ]
