# Generated by Django 5.2 on 2025-09-26 03:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_blogpost_github_url_blogpost_linkedin_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='featured_link_custom',
            field=models.URLField(blank=True, help_text="URL personalizada (solo si tipo es 'URL personalizada')", verbose_name='URL personalizada'),
        ),
        migrations.AddField(
            model_name='project',
            name='featured_link_pdf',
            field=models.FileField(blank=True, help_text="Sube un archivo PDF (solo si tipo es 'Archivo PDF')", upload_to='projects/pdfs/', verbose_name='Archivo PDF'),
        ),
        migrations.AddField(
            model_name='project',
            name='featured_link_post',
            field=models.ForeignKey(blank=True, help_text="Selecciona un post del blog para enlazar (solo si tipo es 'Enlace a Post')", null=True, on_delete=django.db.models.deletion.SET_NULL, to='portfolio.blogpost', verbose_name='Post relacionado'),
        ),
        migrations.AddField(
            model_name='project',
            name='featured_link_type',
            field=models.CharField(choices=[('none', 'Sin enlace'), ('post', 'Enlace a Post'), ('github', 'Usar GitHub URL'), ('demo', 'Usar Demo URL'), ('pdf', 'Archivo PDF'), ('custom', 'URL personalizada')], default='none', help_text='Selecciona qué tipo de enlace mostrar cuando el proyecto aparezca en Featured Work', max_length=10, verbose_name='Tipo de enlace para Featured Work'),
        ),
    ]
