# Generated by Django 5.2 on 2025-09-27 16:21

import django.db.models.deletion
import portfolio.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_project_featured_link_custom_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Nombre')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('color', models.CharField(default='#6c757d', help_text='Color en formato hexadecimal (ej: #ff5722)', max_length=7, verbose_name='Color')),
                ('icon', models.CharField(blank=True, help_text='Clase de Font Awesome (ej: fas fa-newspaper)', max_length=50, verbose_name='Icono')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activa')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Orden')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='featured_image',
            field=models.ImageField(blank=True, upload_to='blog/', validators=[portfolio.validators.ImageValidator(max_height=800, max_size=2097152, max_width=1200, min_height=200, min_width=300), portfolio.validators.validate_no_executable], verbose_name='Imagen destacada'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='post_type',
            field=models.CharField(blank=True, choices=[('news', 'Noticia'), ('tutorial', 'Tutorial'), ('opinion', 'Opinión'), ('project', 'Proyecto'), ('career', 'Carrera')], help_text='Campo deprecated - usar categoría', max_length=20, null=True, verbose_name='Tipo de post (DEPRECATED)'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(upload_to='profile/', validators=[portfolio.validators.ImageValidator(max_height=2000, max_size=2097152, max_width=2000, min_height=100, min_width=100), portfolio.validators.validate_no_executable], verbose_name='Foto de perfil'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='resume_pdf',
            field=models.FileField(blank=True, upload_to='profile/', validators=[portfolio.validators.DocumentValidator(max_size=5242880), portfolio.validators.validate_no_executable], verbose_name='CV en PDF'),
        ),
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(blank=True, upload_to='projects/', validators=[portfolio.validators.ImageValidator(max_height=1080, max_size=3145728, max_width=1920, min_height=150, min_width=200), portfolio.validators.validate_no_executable], verbose_name='Imagen principal'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='category',
            field=models.ForeignKey(blank=True, help_text='Categoría principal del post', null=True, on_delete=django.db.models.deletion.PROTECT, to='portfolio.category', verbose_name='Categoría'),
        ),
    ]
