# Generated by Django 5.2 on 2025-09-27 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_category_alter_blogpost_featured_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='category',
            field=models.CharField(help_text='Ej: Programming, Cloud, Business, Methodologies, etc.', max_length=100, verbose_name='Categoría'),
        ),
    ]
