# Generated by Django 5.2 on 2025-09-27 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0008_remove_category_color_remove_category_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='medium_url',
            field=models.URLField(blank=True, verbose_name='URL de Medium'),
        ),
    ]
