# Generated by Django 5.2 on 2025-09-27 17:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0009_profile_medium_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Nombre')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Orden')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tipo de Proyecto',
                'verbose_name_plural': 'Tipos de Proyectos',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.AlterField(
            model_name='project',
            name='project_type',
            field=models.CharField(blank=True, choices=[('framework', 'Framework'), ('tool', 'Tool'), ('website', 'Website'), ('template', 'Template'), ('dataset', 'Dataset'), ('mobile_app', 'Mobile App'), ('desktop_app', 'Desktop App'), ('library', 'Library'), ('api', 'API'), ('consulting', 'Consulting'), ('strategy', 'Strategy'), ('research', 'Research'), ('process', 'Process'), ('training', 'Training'), ('case_study', 'Case Study'), ('implementation', 'Implementation'), ('other', 'Other')], default='other', help_text='Campo deprecated - usar project_type_obj', max_length=20, null=True, verbose_name='Tipo de proyecto (DEPRECATED)'),
        ),
        migrations.AddField(
            model_name='project',
            name='project_type_obj',
            field=models.ForeignKey(blank=True, help_text='Tipo de proyecto principal', null=True, on_delete=django.db.models.deletion.PROTECT, to='portfolio.projecttype', verbose_name='Tipo de Proyecto'),
        ),
    ]
