# Generated by Django 5.2 on 2025-09-27 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0010_projecttype_alter_project_project_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='emoji',
        ),
        migrations.AlterField(
            model_name='project',
            name='project_type',
            field=models.CharField(blank=True, choices=[('framework', 'Framework'), ('tool', 'Tool'), ('website', 'Website'), ('template', 'Template'), ('dataset', 'Dataset'), ('mobile_app', 'Mobile App'), ('desktop_app', 'Desktop App'), ('library', 'Library'), ('api', 'API'), ('consulting', 'Consulting'), ('strategy', 'Strategy'), ('research', 'Research'), ('process', 'Process'), ('training', 'Training'), ('case_study', 'Case Study'), ('implementation', 'Implementation'), ('other', 'Other')], default='other', help_text='Categoría del proyecto (Framework, Tool, Website, etc.)', max_length=20, null=True, verbose_name='Tipo de proyecto'),
        ),
    ]
