# Generated by Django 5.2 on 2025-09-27 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0011_remove_emoji_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='post_type',
        ),
    ]
