# Generated by Django 5.2 on 2025-10-04 16:56

import portfolio.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0012_remove_blogpost_post_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='resume_pdf_es',
            field=models.FileField(blank=True, help_text='Sube tu currículum en español (formato PDF)', upload_to='profile/', validators=[portfolio.validators.DocumentValidator(max_size=5242880), portfolio.validators.validate_no_executable], verbose_name='CV en PDF (Español)'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(help_text='Sube una imagen cuadrada (misma anchura y altura). Se optimizará automáticamente a 250x250px. Formatos: JPG, PNG, WebP. Máximo 3MB.', upload_to='profile/', validators=[portfolio.validators.ProfileImageValidator(), portfolio.validators.validate_no_executable], verbose_name='Foto de perfil'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='resume_pdf',
            field=models.FileField(blank=True, help_text='Upload your resume in English (PDF format)', upload_to='profile/', validators=[portfolio.validators.DocumentValidator(max_size=5242880), portfolio.validators.validate_no_executable], verbose_name='CV en PDF (English)'),
        ),
    ]
