# Generated by Django 5.2 on 2025-10-09 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0013_add_resume_pdf_es'),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Ej: English, Español, Français', max_length=50, verbose_name='Idioma')),
                ('proficiency', models.CharField(choices=[('A1', 'A1 - Beginner'), ('A2', 'A2 - Elementary'), ('B1', 'B1 - Intermediate'), ('B2', 'B2 - Upper Intermediate'), ('C1', 'C1 - Advanced'), ('C2', 'C2 - Proficient'), ('Native', 'Native')], max_length=10, verbose_name='Nivel de dominio')),
                ('order', models.PositiveIntegerField(default=0, help_text='Orden en que aparecerá en el CV', verbose_name='Orden de visualización')),
            ],
            options={
                'verbose_name': 'Idioma',
                'verbose_name_plural': 'Idiomas',
                'ordering': ['order', 'name'],
            },
        ),
    ]
