# Generated by Django 5.2 on 2025-10-10 02:49

import portfolio.utils.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0015_siteconfiguration'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='siteconfiguration',
            options={'verbose_name': 'Site configuration', 'verbose_name_plural': 'Site configuration'},
        ),
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.TextField(verbose_name='Biografia'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='location',
            field=models.CharField(max_length=100, verbose_name='Ubicacion'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Telefono'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(help_text='Sube una imagen cuadrada (misma anchura y altura). Se optimizara automaticamente a 250x250px. Formatos: JPG, PNG, WebP. Maximo 3MB.', upload_to='profile/', validators=[portfolio.utils.validators.ProfileImageValidator(), portfolio.utils.validators.validate_no_executable], verbose_name='Foto de perfil'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='resume_pdf_es',
            field=models.FileField(blank=True, help_text='Sube tu curriculum en espanol (formato PDF)', upload_to='profile/', validators=[portfolio.utils.validators.DocumentValidator(max_size=5242880), portfolio.utils.validators.validate_no_executable], verbose_name='CV en PDF (Espanol)'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Titulo profesional'),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='auto_translate_enabled',
            field=models.BooleanField(default=False, verbose_name='Enable automatic translation'),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='default_language',
            field=models.CharField(choices=[('en', 'English'), ('es', 'Espanol')], default='en', max_length=10, verbose_name='Default language'),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='translation_api_key',
            field=models.CharField(blank=True, max_length=255, verbose_name='Translation service API key'),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='translation_api_url',
            field=models.URLField(blank=True, verbose_name='Translation service URL'),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='translation_provider',
            field=models.CharField(choices=[('libretranslate', 'LibreTranslate')], default='libretranslate', max_length=50, verbose_name='Translation provider'),
        ),
    ]
