# Generated by Django 5.2 on 2025-10-10 15:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0018_project_translations'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='profile',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='project',
            managers=[
            ],
        ),
        migrations.AlterField(
            model_name='project',
            name='featured_link_post',
            field=models.ForeignKey(blank=True, help_text="Selecciona un post del blog para enlazar (solo si tipo es 'Enlace a Post')", null=True, on_delete=django.db.models.deletion.SET_NULL, to='portfolio.blogpost', verbose_name='Post relacionado'),
        ),
    ]
