# Generated by Django 5.2 on 2025-10-10 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0021_translate_experience_education_skill_category'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='blogpost',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='category',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='education',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='experience',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='skill',
            managers=[
            ],
        ),
        migrations.AlterField(
            model_name='language',
            name='name',
            field=models.CharField(help_text='Ej: English, Espanol, Francais', max_length=50, verbose_name='Idioma'),
        ),
        migrations.AlterField(
            model_name='language',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Orden en que aparecera en el CV', verbose_name='Orden de visualizacion'),
        ),
    ]
