# Generated by Django 5.2 on 2025-10-11 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0025_auto_translation_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteconfiguration',
            name='translation_api_key',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Translation service API key'),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='translation_api_url',
            field=models.URLField(blank=True, default='http://libretranslate:5000', verbose_name='Translation service URL'),
        ),
    ]
