# Generated by Django 5.0.4 on 2025-10-12 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0027_alter_siteconfiguration_translation_api_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='Email'),
        ),
        migrations.AlterUniqueTogether(
            name='profiletranslation',
            unique_together={('language_code', 'master'), ('language_code', 'name')},
        ),
    ]
