# Generated by Django 5.2 on 2025-10-13 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0029_cleanup_category_table'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Technology',
            new_name='KnowledgeBase',
        ),
        migrations.RenameModel(
            old_name='TechnologyTranslation',
            new_name='KnowledgeBaseTranslation',
        ),
        migrations.AlterModelOptions(
            name='knowledgebase',
            options={'ordering': ['translations__name'], 'verbose_name': 'Base de Conocimiento', 'verbose_name_plural': 'Bases de Conocimiento'},
        ),
        migrations.AlterModelOptions(
            name='knowledgebasetranslation',
            options={'default_permissions': (), 'managed': True, 'verbose_name': 'Base de Conocimiento Translation'},
        ),
        migrations.RemoveField(
            model_name='project',
            name='technologies',
        ),
        migrations.AddField(
            model_name='project',
            name='knowledge_bases',
            field=models.ManyToManyField(to='portfolio.knowledgebase', verbose_name='Bases de Conocimiento'),
        ),
        migrations.AlterModelTable(
            name='knowledgebasetranslation',
            table='portfolio_knowledgebase_translation',
        ),
    ]
