# Generated by Django 5.2 on 2025-10-13

from django.db import migrations
from django.utils.text import slugify


CATEGORIES = [
    {
        "order": 1,
        "en": {"name": "Idea", "description": "Early concepts, brainstorming and product discovery notes."},
        "es": {"name": "Idea", "description": "Conceptos iniciales, lluvia de ideas y notas de descubrimiento."},
    },
    {
        "order": 2,
        "en": {"name": "Tutorial", "description": "How-to guides and walkthroughs to learn new skills."},
        "es": {"name": "Tutorial", "description": "Guías paso a paso para aprender nuevas habilidades."},
    },
    {
        "order": 3,
        "en": {"name": "News", "description": "Announcements, launches and professional updates."},
        "es": {"name": "Noticias", "description": "Anuncios, lanzamientos y novedades profesionales."},
    },
    {
        "order": 4,
        "en": {"name": "Review", "description": "Opinions on tools, books, events or industry trends."},
        "es": {"name": "Reseña", "description": "Opiniones sobre herramientas, libros, eventos o tendencias."},
    },
    {
        "order": 5,
        "en": {"name": "Case Study", "description": "Detailed analyses of delivered projects and outcomes."},
        "es": {"name": "Caso de estudio", "description": "Análisis detallados de proyectos entregados y resultados."},
    },
]

def create_default_categories(apps, schema_editor):
    Category = apps.get_model("portfolio", "Category")
    CategoryTranslation = apps.get_model("portfolio", "CategoryTranslation")
    connection = schema_editor.connection
    cursor = connection.cursor()

    for entry in CATEGORIES:
        slug = slugify(entry["en"]["name"])
        en_name = entry["en"]["name"]

        # Check if category already exists
        cursor.execute("SELECT id FROM portfolio_category WHERE slug = %s", [slug])
        row = cursor.fetchone()

        if row:
            category_id = row[0]
        else:
            # Use raw SQL to insert since PostgreSQL still has legacy 'name' and 'description' columns
            cursor.execute(
                "INSERT INTO portfolio_category (slug, is_active, \"order\", name, description, created_at, updated_at) "
                "VALUES (%s, %s, %s, %s, %s, NOW(), NOW()) RETURNING id",
                [slug, True, entry["order"], en_name, entry["en"]["description"]]
            )
            category_id = cursor.fetchone()[0]

        # Create or update English translation
        cursor.execute(
            "SELECT id FROM portfolio_category_translation WHERE master_id = %s AND language_code = %s",
            [category_id, "en"]
        )
        if cursor.fetchone():
            cursor.execute(
                "UPDATE portfolio_category_translation SET name = %s, description = %s "
                "WHERE master_id = %s AND language_code = %s",
                [entry["en"]["name"], entry["en"]["description"], category_id, "en"]
            )
        else:
            cursor.execute(
                "INSERT INTO portfolio_category_translation (master_id, language_code, name, description) "
                "VALUES (%s, %s, %s, %s)",
                [category_id, "en", entry["en"]["name"], entry["en"]["description"]]
            )

        # Create or update Spanish translation
        cursor.execute(
            "SELECT id FROM portfolio_category_translation WHERE master_id = %s AND language_code = %s",
            [category_id, "es"]
        )
        if cursor.fetchone():
            cursor.execute(
                "UPDATE portfolio_category_translation SET name = %s, description = %s "
                "WHERE master_id = %s AND language_code = %s",
                [entry["es"]["name"], entry["es"]["description"], category_id, "es"]
            )
        else:
            cursor.execute(
                "INSERT INTO portfolio_category_translation (master_id, language_code, name, description) "
                "VALUES (%s, %s, %s, %s)",
                [category_id, "es", entry["es"]["name"], entry["es"]["description"]]
            )



def remove_default_categories(apps, schema_editor):
    Category = apps.get_model("portfolio", "Category")
    slugs = [slugify(entry["en"]["name"]) for entry in CATEGORIES]
    Category.objects.filter(slug__in=slugs).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0031_create_default_knowledge_bases"),
    ]

    operations = [
        migrations.RunPython(create_default_categories, remove_default_categories),
    ]

