# Generated by Django 5.2 on 2025-10-13

from django.db import migrations
from django.utils.text import slugify


CATEGORIES = [
    {
        "order": 1,
        "en": {"name": "Idea", "description": "Early concepts, brainstorming and product discovery notes."},
        "es": {"name": "Idea", "description": "Conceptos iniciales, lluvia de ideas y notas de descubrimiento."},
    },
    {
        "order": 2,
        "en": {"name": "Tutorial", "description": "How-to guides and walkthroughs to learn new skills."},
        "es": {"name": "Tutorial", "description": "Guías paso a paso para aprender nuevas habilidades."},
    },
    {
        "order": 3,
        "en": {"name": "News", "description": "Announcements, launches and professional updates."},
        "es": {"name": "Noticias", "description": "Anuncios, lanzamientos y novedades profesionales."},
    },
    {
        "order": 4,
        "en": {"name": "Review", "description": "Opinions on tools, books, events or industry trends."},
        "es": {"name": "Reseña", "description": "Opiniones sobre herramientas, libros, eventos o tendencias."},
    },
    {
        "order": 5,
        "en": {"name": "Case Study", "description": "Detailed analyses of delivered projects and outcomes."},
        "es": {"name": "Caso de estudio", "description": "Análisis detallados de proyectos entregados y resultados."},
    },
]

def create_default_categories(apps, schema_editor):
    Category = apps.get_model("portfolio", "Category")
    CategoryTranslation = apps.get_model("portfolio", "CategoryTranslation")

    for entry in CATEGORIES:
        slug = slugify(entry["en"]["name"])

        category, _ = Category.objects.get_or_create(
            slug=slug,
            defaults={"is_active": True, "order": entry["order"]},
        )

        CategoryTranslation.objects.update_or_create(
            master=category, language_code="en",
            defaults={
                "name": entry["en"]["name"],
                "description": entry["en"]["description"],
            },
        )
        CategoryTranslation.objects.update_or_create(
            master=category, language_code="es",
            defaults={
                "name": entry["es"]["name"],
                "description": entry["es"]["description"],
            },
        )



def remove_default_categories(apps, schema_editor):
    Category = apps.get_model("portfolio", "Category")
    slugs = [slugify(entry["en"]["name"]) for entry in CATEGORIES]
    Category.objects.filter(slug__in=slugs).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0031_create_default_knowledge_bases"),
    ]

    operations = [
        migrations.RunPython(create_default_categories, remove_default_categories),
    ]

