# Generated by Django 5.2 on 2025-10-13

from django.db import migrations
from django.utils.text import slugify


PROJECT_TYPES = [
    {
        "order": 0,
        "en": {
            "name": "Consulting",
            "description": "Advisory engagements delivering assessments, roadmaps and expert guidance.",
        },
        "es": {
            "name": "Consultoría",
            "description": "Proyectos de asesoría con diagnósticos, roadmaps y acompañamiento experto.",
        },
    },
    {
        "order": 1,
        "en": {
            "name": "Product Development",
            "description": "End-to-end delivery of digital products, SaaS platforms or mobile experiences.",
        },
        "es": {
            "name": "Producto",
            "description": "Entrega integral de productos digitales, plataformas SaaS o experiencias móviles.",
        },
    },
    {
        "order": 2,
        "en": {
            "name": "Implementation",
            "description": "Technical rollouts, integrations and system deployments with measurable impact.",
        },
        "es": {
            "name": "Implementación",
            "description": "Despliegues técnicos, integraciones y puestas en marcha con impacto medible.",
        },
    },
    {
        "order": 3,
        "en": {
            "name": "Research & Development",
            "description": "Proofs of concept, experimentation and innovation initiatives.",
        },
        "es": {
            "name": "Research & Development",
            "description": "Pruebas de concepto, experimentación e iniciativas de innovación.",
        },
    },
    {
        "order": 4,
        "en": {
            "name": "Strategy",
            "description": "Vision definition, prioritisation frameworks and long-term planning.",
        },
        "es": {
            "name": "Estrategia",
            "description": "Definición de visión, marcos de priorización y planificación a largo plazo.",
        },
    },
    {
        "order": 5,
        "en": {
            "name": "Automation & Integrations",
            "description": "Pipelines, bots and system integrations that streamline operations.",
        },
        "es": {
            "name": "Automatización e Integraciones",
            "description": "Pipelines, bots e integraciones que agilizan operaciones.",
        },
    },
    {
        "order": 6,
        "en": {
            "name": "Business Intelligence",
            "description": "Analytics solutions, dashboards and data products for decision making.",
        },
        "es": {
            "name": "Business Intelligence",
            "description": "Soluciones analíticas, dashboards y productos de datos para la toma de decisiones.",
        },
    },
    {
        "order": 7,
        "en": {
            "name": "Training & Enablement",
            "description": "Workshops, bootcamps and tailored programmes to grow team capabilities.",
        },
        "es": {
            "name": "Capacitación",
            "description": "Workshops, bootcamps y programas a medida para potenciar equipos.",
        },
    },
    {
        "order": 8,
        "en": {
            "name": "Infrastructure & DevOps",
            "description": "Cloud architectures, observability and operational excellence initiatives.",
        },
        "es": {
            "name": "Infraestructura",
            "description": "Arquitecturas cloud, observabilidad e iniciativas de excelencia operativa.",
        },
    },
    {
        "order": 9,
        "en": {
            "name": "Business Development",
            "description": "Growth initiatives, partnerships and go-to-market expansion.",
        },
        "es": {
            "name": "Desarrollo de Negocios",
            "description": "Iniciativas de crecimiento, alianzas y expansión comercial.",
        },
    },
    {
        "order": 10,
        "en": {
            "name": "Innovation",
            "description": "Ideation, prototyping and validation of emerging opportunities.",
        },
        "es": {
            "name": "Innovación",
            "description": "Ideación, prototipado y validación de oportunidades emergentes.",
        },
    },
]


def create_default_project_types(apps, schema_editor):
    ProjectType = apps.get_model("portfolio", "ProjectType")
    ProjectTypeTranslation = apps.get_model("portfolio", "ProjectTypeTranslation")
    connection = schema_editor.connection
    cursor = connection.cursor()

    for entry in PROJECT_TYPES:
        slug = slugify(entry["en"]["name"])

        # Check if project type already exists
        cursor.execute("SELECT id FROM portfolio_projecttype WHERE slug = %s", [slug])
        row = cursor.fetchone()

        if row:
            project_type_id = row[0]
        else:
            # Use raw SQL to insert since PostgreSQL still has legacy 'name' and 'description' columns
            cursor.execute(
                "INSERT INTO portfolio_projecttype (slug, is_active, \"order\", name, description, created_at, updated_at) "
                "VALUES (%s, %s, %s, %s, %s, NOW(), NOW()) RETURNING id",
                [slug, True, entry["order"], entry["en"]["name"], entry["en"]["description"]]
            )
            project_type_id = cursor.fetchone()[0]

        # Create or update English translation
        cursor.execute(
            "SELECT id FROM portfolio_projecttype_translation WHERE master_id = %s AND language_code = %s",
            [project_type_id, "en"]
        )
        if cursor.fetchone():
            cursor.execute(
                "UPDATE portfolio_projecttype_translation SET name = %s, description = %s "
                "WHERE master_id = %s AND language_code = %s",
                [entry["en"]["name"], entry["en"]["description"], project_type_id, "en"]
            )
        else:
            cursor.execute(
                "INSERT INTO portfolio_projecttype_translation (master_id, language_code, name, description) "
                "VALUES (%s, %s, %s, %s)",
                [project_type_id, "en", entry["en"]["name"], entry["en"]["description"]]
            )

        # Create or update Spanish translation
        cursor.execute(
            "SELECT id FROM portfolio_projecttype_translation WHERE master_id = %s AND language_code = %s",
            [project_type_id, "es"]
        )
        if cursor.fetchone():
            cursor.execute(
                "UPDATE portfolio_projecttype_translation SET name = %s, description = %s "
                "WHERE master_id = %s AND language_code = %s",
                [entry["es"]["name"], entry["es"]["description"], project_type_id, "es"]
            )
        else:
            cursor.execute(
                "INSERT INTO portfolio_projecttype_translation (master_id, language_code, name, description) "
                "VALUES (%s, %s, %s, %s)",
                [project_type_id, "es", entry["es"]["name"], entry["es"]["description"]]
            )


def remove_default_project_types(apps, schema_editor):
    ProjectType = apps.get_model("portfolio", "ProjectType")
    slugs = [slugify(entry["en"]["name"]) for entry in PROJECT_TYPES]
    ProjectType.objects.filter(slug__in=slugs).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0032_create_default_categories"),
    ]

    operations = [
        migrations.RunPython(create_default_project_types, remove_default_project_types),
    ]

