# Generated by Django 5.2 on 2025-12-08 02:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0034_fix_language_table'),
    ]

    def deduplicate_data(apps, schema_editor):
        from django.db import transaction
        from parler.utils.context import switch_language
        
        ProjectType = apps.get_model('portfolio', 'ProjectType')
        Project = apps.get_model('portfolio', 'Project')
        Skill = apps.get_model('portfolio', 'Skill')
        
        # --- Deduplicate ProjectTypes ---
        all_ids = ProjectType.objects.values_list('id', flat=True).distinct()
        by_name = {}
        
        for pid in all_ids:
            pt = ProjectType.objects.get(id=pid)
            
            # Helper to get name from translations manually since we are in a migration
            # We look at the translations table directly via related manager if possible,
            # but apps.get_model might limit us.
            # Using simple iteration over translations if available.
            name = None
            try:
                # Try getting English translation first
                trans = pt.translations.filter(language_code='en').first()
                if trans:
                    name = trans.name
                else:
                    # Fallback to any
                    trans = pt.translations.first()
                    if trans:
                        name = trans.name
            except Exception:
                continue

            if not name:
                continue

            name_key = name.strip().lower()
            if name_key not in by_name:
                by_name[name_key] = []
            by_name[name_key].append(pt)

        for name_key, pts in by_name.items():
            if len(pts) > 1:
                pts.sort(key=lambda x: x.id)
                keep = pts[0]
                discard = pts[1:]
                
                for pt in discard:
                    if pt.id == keep.id:
                        continue
                    # Update related projects
                    Project.objects.filter(project_type_obj_id=pt.id).update(project_type_obj_id=keep.id)
                    pt.delete()

        # --- Deduplicate Skills (Knowledge Bases) ---
        # Same logic for skills
        all_skill_ids = Skill.objects.values_list('id', flat=True).distinct()
        skills_by_name = {}

        for pid in all_skill_ids:
            skill = Skill.objects.get(id=pid)
            name = None
            try:
                trans = skill.translations.filter(language_code='en').first()
                if trans:
                    name = trans.name
                else:
                    trans = skill.translations.first()
                    if trans:
                        name = trans.name
            except Exception:
                continue
            
            if not name:
                continue
                
            name_key = name.strip().lower()
            if name_key not in skills_by_name:
                skills_by_name[name_key] = []
            skills_by_name[name_key].append(skill)

        for name_key, skills in skills_by_name.items():
            if len(skills) > 1:
                skills.sort(key=lambda x: x.id)
                keep_skill = skills[0]
                discard_skills = skills[1:]
                
                for skill in discard_skills:
                    if skill.id == keep_skill.id:
                        continue
                        
                    # We need to handle ManyToMany relations manually for Project.knowledge_bases
                    # Find projects using the discarded skill
                    projects_with_skill = Project.objects.filter(knowledge_bases=skill)
                    for proj in projects_with_skill:
                        proj.knowledge_bases.remove(skill)
                        proj.knowledge_bases.add(keep_skill)
                    
                    skill.delete()

    operations = [
        migrations.RunPython(deduplicate_data),
    ]
