# Generated by Django 5.2 on 2025-12-09 03:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0035_remove_duplicates'),
    ]

    operations = [
        migrations.RunSQL(
            sql="ALTER TABLE portfolio_category DROP COLUMN IF EXISTS name;",
            reverse_sql="ALTER TABLE portfolio_category ADD COLUMN name VARCHAR(100) NULL;"
        ),
        migrations.RunSQL(
            sql="ALTER TABLE portfolio_category DROP COLUMN IF EXISTS description;",
            reverse_sql="ALTER TABLE portfolio_category ADD COLUMN description TEXT NULL;"
        ),
    ]
