# Generated by Django 5.2.9 on 2026-01-20 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0037_alter_blogpost_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteconfiguration',
            name='translation_timeout',
            field=models.PositiveIntegerField(default=60, verbose_name='Tiempo de espera (segundos)'),
        ),
    ]
