# Generated by Django 5.2.12 on 2026-08-08 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0038_alter_siteconfiguration_translation_timeout'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='newsletter_button_text',
            field=models.CharField(blank=True, default='', help_text="Optional. Replaces the generic 'Subscribe' label.", max_length=50, verbose_name='Newsletter button text'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='newsletter_description',
            field=models.CharField(blank=True, default='', help_text='Optional. Replaces the generic description.', max_length=255, verbose_name='Newsletter description'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='newsletter_title',
            field=models.CharField(blank=True, default='', help_text="Optional. Replaces the generic 'Newsletter' heading.", max_length=100, verbose_name='Newsletter title'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='newsletter_url',
            field=models.URLField(blank=True, default='', help_text='Destination of the end-of-post subscribe button. Leave empty to keep the contact CTA.', verbose_name='Newsletter URL'),
        ),
    ]
