# Generated by Django 5.2.12 on 2026-08-09 00:59

import portfolio.utils.uploads
import portfolio.utils.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0039_siteconfiguration_newsletter_button_text_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='featured_image',
            field=models.ImageField(blank=True, upload_to=portfolio.utils.uploads.UUIDUploadTo('blog'), validators=[portfolio.utils.validators.ImageValidator(max_height=800, max_size=2097152, max_width=1200, min_height=200, min_width=300), portfolio.utils.validators.validate_no_executable], verbose_name='Imagen destacada'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(help_text='Sube una imagen cuadrada (misma anchura y altura). Se optimizará automáticamente a 250x250px. Formatos: JPG, PNG, WebP. Máximo 3MB.', upload_to=portfolio.utils.uploads.UUIDUploadTo('profile'), validators=[portfolio.utils.validators.ProfileImageValidator(), portfolio.utils.validators.validate_no_executable], verbose_name='Foto de perfil'),
        ),
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(blank=True, upload_to=portfolio.utils.uploads.UUIDUploadTo('projects'), validators=[portfolio.utils.validators.ImageValidator(max_height=1080, max_size=3145728, max_width=1920, min_height=150, min_width=200), portfolio.utils.validators.validate_no_executable], verbose_name='Imagen principal'),
        ),
    ]
