# Generated by Django 5.2.15 on 2026-08-09 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0040_alter_blogpost_featured_image_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='blogposttranslation',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='categorytranslation',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='educationtranslation',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='experiencetranslation',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='knowledgebasetranslation',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='languagetranslation',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='profiletranslation',
            unique_together={('language_code', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='projecttranslation',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='projecttypetranslation',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='skilltranslation',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='blogposttranslation',
            constraint=models.UniqueConstraint(fields=('language_code', 'master'), name='portfolio_blogpost_translation_uniq_lang'),
        ),
        migrations.AddConstraint(
            model_name='categorytranslation',
            constraint=models.UniqueConstraint(fields=('language_code', 'master'), name='portfolio_category_translation_uniq_lang'),
        ),
        migrations.AddConstraint(
            model_name='educationtranslation',
            constraint=models.UniqueConstraint(fields=('language_code', 'master'), name='portfolio_education_translation_uniq_lang'),
        ),
        migrations.AddConstraint(
            model_name='experiencetranslation',
            constraint=models.UniqueConstraint(fields=('language_code', 'master'), name='portfolio_experience_translation_uniq_lang'),
        ),
        migrations.AddConstraint(
            model_name='knowledgebasetranslation',
            constraint=models.UniqueConstraint(fields=('language_code', 'master'), name='portfolio_knowledgebase_translation_uniq_lang'),
        ),
        migrations.AddConstraint(
            model_name='languagetranslation',
            constraint=models.UniqueConstraint(fields=('language_code', 'master'), name='portfolio_language_translation_uniq_lang'),
        ),
        migrations.AddConstraint(
            model_name='profiletranslation',
            constraint=models.UniqueConstraint(fields=('language_code', 'master'), name='portfolio_profile_translation_uniq_lang'),
        ),
        migrations.AddConstraint(
            model_name='projecttranslation',
            constraint=models.UniqueConstraint(fields=('language_code', 'master'), name='portfolio_project_translation_uniq_lang'),
        ),
        migrations.AddConstraint(
            model_name='projecttypetranslation',
            constraint=models.UniqueConstraint(fields=('language_code', 'master'), name='portfolio_projecttype_translation_uniq_lang'),
        ),
        migrations.AddConstraint(
            model_name='skilltranslation',
            constraint=models.UniqueConstraint(fields=('language_code', 'master'), name='portfolio_skill_translation_uniq_lang'),
        ),
    ]
