# Generated by Django 5.2.15 on 2026-08-09 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0041_parler24_unique_constraints'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='umami_script_url',
            field=models.URLField(blank=True, default='', help_text='Full URL of the Umami tracking script, e.g. https://stats.example.com/script.js. Leave empty to disable analytics.', verbose_name='Umami script URL'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='umami_website_id',
            field=models.CharField(blank=True, default='', help_text='Website ID from your Umami dashboard.', max_length=64, verbose_name='Umami website ID'),
        ),
    ]
